### DISCUSSION TITLE
What does the `validator.pattern` actually affect?

### DISCUSSION THREAD

**Discussion by ranma2913** [github/safe-settings#518] [Q&A]
I'm looking through the code, documentation, examples and see:

```yaml
validator:
  #pattern: '[a-zA-Z0-9_-]+_[a-zA-Z0-9_-]+.*' 
  pattern: '[a-zA-Z0-9_-]+'
```

I can't find a clear explanation of what that affects and when I should/shouldn't use it.

I did find this in the README.md 
![image](https://github.com/github/safe-settings/assets/4295880/3f4bfdc2-321e-42ff-9865-4f94545bd90f) is it safe to say that refers to `validator.pattern` in a suborg or org settings.yml?
