### DISCUSSION TITLE
Is it possible to adjust a ruleset from the suborg level on the repo level?

### DISCUSSION THREAD

**Discussion by Wittenborn** [github/safe-settings#678] [Q&A]
I have a suborg which defines a ruleset that contains a rule that requires PRs of at least 2 reviewers.

```
rulesets:
  - name: "Suborg PR"
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include: ["refs/heads/main"]
        exclude: []
    rules:
      - type: pull_request
        parameters:
          dismiss_stale_reviews_on_push: true
          require_code_owner_review: true
          require_last_push_approval: true
          required_approving_review_count: 2
          required_review_thread_resolution: true
```

Is it possible to adapt the ruleset so that only one reviewer is required for certain repos? 

I tried to define a ruleset for a specific repo with the same name "Suborg PR", but then I get a validation error. And I would assume that if I create another ruleset with a different name on the repo level that both rulesets are created and that the more restricitve rule with 2 required reviewers is still applied.
