### ISSUE TITLE
allow_force_push flag is always disabled, with no way to configure

### ISSUE THREAD

**Issue by dan-ih** [github/safe-settings#215]
## Problem Description
When branch protection is applied/enforced by safe-settings, the allow_force_push flag is always reset to 'disabled', and it appears there's no way to configure this setting for a repo.

### What is actually happening
See above

### What is the expected behavior
Wither 'allow_force_push' should not be changed if it is not configured by safe settings, or there should be a way to configure it in the repo protections file.

### Are you using the hosted instance of probot/settings or running your own?
Running our own

### If running your own instance, are you using it with github.com or GitHub Enterprise?
github.com

#### Version of probot/settings
1.1.9

#### Version of GitHub Enterprise
N/A

**Comment by aakash-pinc** [comment]
@decyjphr: Any idea when this will be fixed?  We added a custom configuration for one branch like below in the YAML file and it is not reflected in GitHub

```
protection:
  allow_force_pushes:
    enabled: true
```

**Comment by decyjphr** [comment]
I'll take a look at it tomorrow and let you know if it can be fixed quickly. Thanks for raising this.

**Comment by decyjphr** [comment]
@aakash-pinc The configuration you had is not correct. It would be like this: (_there is no `enabled` field under `allow_force_pushes`_)
```yaml
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 2
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
      allow_force_pushes: true
```
I tested the above config and it works...
