### ISSUE TITLE
Inheritance, hierarchy in branch configuration

### ISSUE THREAD

**Issue by svg153** [github/safe-settings#247]
## New Feature

We started using `required_status_checks` manage by safe-settings, but due to its behavior, we stopped using it because it did not meet what we wanted.
We want to have `required_pull_request_reviews` at the organization level, and `required_status_checks` with the common ones at the organization level, extend for some repositories and remove for others (`required_status_checks: []`).

Therefore, what we were looking for:
`.github/settings.yaml`
```yaml
branches:
  - name: default
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "🔃 pre-commit"
      enforce_admins: true
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
      block_creations: true
      required_conversation_resolution: true
```

`.github/repos/example.yml`
```yaml
branches:
  - name: default
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Lint, compile and build"
```

And we had to do something like this:

`.github/repos/example.yml`
```yaml
branches:
  # CAUTION: before edit check default config in .github/settings.yml
  #   safe-settings do not merge config for branches, so you need to copy base
  #   config from .github/settings.yml and modify it with your repository config
  - name: default
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "🔃 pre-commit"
          - "Lint, compile and build"
      enforce_admins: true
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
      block_creations: true
      required_conversation_resolution: true
```

We also couldn't leave all the checks at the organization level because in the repositories that don't have those actions, the `required_status_checks` stays waiting, but nobody will validate it and the PR cannot be merged.
