### ISSUE TITLE
Support for Branch Protection bypass_pull_request_allowances

### ISSUE THREAD

**Issue by mike-stewart** [github/safe-settings#249]
## New Feature

Can safe-settings add support for the "Allow specified actors to bypass required pull requests" feature of required pull request reviews for branch protection?

> * Is the functionality available in the GitHub UI? If so, please provide a link to information about the feature.

Available in the UI as:
```
Allow specified actors to bypass required pull requests
Specify people, teams, or apps who are allowed to bypass required pull requests.
```
<img width="791" alt="Screen Shot 2022-07-25 at 10 41 15 AM" src="https://user-images.githubusercontent.com/2521245/180791415-6d3e9e50-08dc-4cae-861b-6a00e014f5f9.png">

> * Is the functionality available through the GitHub API? If the functionality is available, please provide links to the
  API documentation (https://developer.github.com/v3/) as well as the Octokit documentation (https://octokit.github.io/).

Available in the [API](https://docs.github.com/en/rest/branches/branch-protection#update-branch-protection) as "bypass_pull_request_allowances".

**Comment by decyjphr** [comment]
Thanks, will add this in the coming weeks.

**Comment by dan-ih** [comment]
Any progress on this @decyjphr  ?

**Comment by ghost** [comment]
I would also be interested to know when this is coming out :)

**Comment by viks-confluent** [comment]
@decyjphr  any update on this would be appreciated. Thanks

**Comment by martinm82** [comment]
Aren't the attributes out of the box available in safe-settings?

Also should actually all the boolean parameters available in the API (https://docs.github.com/en/rest/branches/branch-protection#update-branch-protection) be added to the reformat function? (e.g. allow_force_pushes, block_creations, lock_branch, allow_fork_syncing)

**Comment by ghost** [comment]
@mike-stewart @dan-ih @viks-confluent  It seems @decyjphr has already implemented this 😄!
So, i did a little bit of test and yes, the attributes are already available it's just that it is not mentioned in the documentation/examples, here is how i used them and it worked:
By defining:
```
bypass_pull_request_allowances:
          users: [ "GranitFazliuRB","User2","User3"]
```
under the **required_pull_request_reviews** section

Only tested it with users but it should work with **teams** and **apps** arrays as well
```
branches:
  - name: default
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        bypass_pull_request_allowances:
          users: [ "GranitFazliuRB","User2","User3"]        
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: []
```
