### ISSUE TITLE
Warning: possible change in GH API may cause issues with safe-settings

### ISSUE THREAD

**Issue by markjm** [github/safe-settings#255]
On latest versions:

When a change is triggered and safe-settings runs for a repository, the first change made is for repository settings. Something like 

```
DEBUG (mark): GitHub request: PATCH https://api.github.com/repos/ORG/REPO - 422
    auto_init: true
    visibility: "internal"
    has_issues: false
    has_projects: false
    has_wiki: false
    allow_squash_merge: true
    allow_merge_commit: false
    allow_rebase_merge: false
    allow_auto_merge: true
    delete_branch_on_merge: true
    org: "REDACTED"
```

This request, however, has started to fail with the below message:

`"data":{"message":"Visibility is already internal.","documentation_url":"https://github.com/pricing"}}`

In case its relevant: this request also has the nebula header enabled `"headers":{"accept":"application/vnd.github.nebula-preview+json"`

I do not know where/how to track down possible changes to GH API that might cause this :/

cc @decyjphr

**Comment by markjm** [comment]
@decyjphr can you please confirm that this is new and broken? or is this just something I only noticed now but not a blocker?

**Comment by decyjphr** [comment]
I have never seen this before and other customers have not seen this either which makes me think this is new. I have asked GitHub engineering if anything changed in the api.

**Comment by decyjphr** [comment]
@markjm I tried to recreate this with a test repo., but couldn't. Here is the output from the logs
```
DEBUG (event): Updating repo with settings ["blue","green","yellow","red","uber","newone","green","blue"] {"mediaType":{"previews":["nebula-preview"]},"name":"test","org":"dec","force_create":true,"description":"description of test repository","homepage":"https://newhome.github.io/home","visibility":"internal","auto_init":true,"has_issues":true,"has_projects":true,"has_wiki":true,"has_downloads":true,"allow_squash_merge":true,"allow_merge_commit":false,"allow_rebase_merge":false,"default_branch":"develop","repo":"test","owner":"dec"}
    id: "c7198708-1789-11ed-8577-96afb59dcb6b"
DEBUG (test): GitHub request: PATCH https://api.github.com/repos/dec/test - 200
    org: "dec"
    force_create: true
    description: "description of test repository"
    homepage: "https://newhome.github.io/home"
    visibility: "internal"
    auto_init: true
    has_issues: true
    has_projects: true
    has_wiki: true
    has_downloads: true
    allow_squash_merge: true
    allow_merge_commit: false
    allow_rebase_merge: false
    default_branch: "develop"
```
 I'll try different combinations to recreate your error. Let me know if I am missing anything. The settings are:
```yaml
repository:      
  name: test     
  org: dec
  force_create: true 
  description: description of test repository
  homepage: https://newhome.github.io/home
  topics: 
  - blue 
  - green  
  - yellow 
  - red
  visibility: internal
  auto_init: true    
  has_issues: true   
  has_projects: true
  has_wiki: true
  has_downloads: true
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false 
  default_branch: develop 
```
