### ISSUE TITLE
Adding webhook URL as settings

### ISSUE THREAD

**Issue by amartyaroy** [github/safe-settings#266]
Hi @decyjphr 
I am wondering if this is possible or not.
With the latest release I found that we have the option to add the autolink reference. So can we add the webhook urls also from the central repo settings just like the admin repo.
Can it be possible ? Or any sort of enhancement in this regard would be great

**Comment by abhishekmukherg** [comment]
My team is also really interested in this.

On the assumption that this is a feature that we'd want (not saying that's true), thought I'd start sketching out a DSL for it.

Here are all the API parameters made into yaml-ish:

```yaml
webhooks:
- url: https://www.example.com
  content_type: json|form
  secret: # hmmm. this is a tough one. how would we want this accomplished?
  insecure_ssl: true|false
  events:
  - push
  - pull_request
  active: true|false  # i think we leave this out -- users can just leverage their git history if they want to resurrect a webhook
```

The difficulties with the above seem to be largely around the `secret` management. Reconciliation would probably delete any webhook that doesn't match the URL -- it's a bit more churn than strictly necessary but way easier.
