### ISSUE TITLE
SafeSettings removes existing team permission for all the repos

### ISSUE THREAD

**Issue by sajithvasu** [github/safe-settings#350]
Github Safesettings app removes the existing teams permissions for all existing repositories within the org when the following mentioned settings are enabled. On the other hand, documentation does not specify removal of any existing permission when controlled through safesettings app. Is this the expected behavior? 

**settings.yml**
```
repository:
teams:
  - name: <team_name>
    permission: <team_permission>
```

Our goal is to add specific permissions/teams to all the existing/new repos without impacting existing team permission for all the repos.
