### ISSUE TITLE
The `auto_init: true` option is not working

### ISSUE THREAD

**Issue by LamarrD** [github/safe-settings#360]
## Problem Description
We have safe-settings hosted in our GitHub organization using serverless framework. When an empty repo is created it does not inherit the global settings hosted in our admin repo. As a test, I created:

* test-repo-empty
* test-repo-empty-with-readme

Additionally, we also run safe-settings on a [cron lambda](https://github.com/github/safe-settings/issues/313). After a readme was created on `test-repo-empty` the cron lambda picked it up and successfully applied the global settings.

### What is actually happening
The `test-repo-empty` repo was unmodified.
The `test-repo-empty-with-readme` repo inherited the global settings.

### What is the expected behavior
Both repos inherit the global settings.

### Error output, if available
There was no error in the logs. 

### Are you using the hosted instance of probot/settings or running your own?
We are running our own hosted instance using serverless framework.

### If running your own instance, are you using it with github.com or GitHub Enterprise?
We are using it with github.com

#### Version of probot/settings
2.0.7

#### Version of GitHub Enterprise
N/A

**Comment by sfc-gh-smisra** [comment]
I am experiencing the same bug

**Comment by oitTim** [comment]
We are installing this via a helm chart (2.1.10) in a GHE (3.13.0) environment, and are experiencing the exact same issue.

Description, private, website, labels, teams and collaborators all get applied ... but the repository is never initialized.  Anything that revolves around referencing a branch fails, like branch protection rules.

However as soon as the repository is manually initialized, everything gets applied from the admin repository as it should.  

When looking at the safe-setting logs it clearly states why it can't apply the rules:

**"Cannot update default branch for an empty repository. Please init the repository and push first"**

or

**"Error applying branch protection" "Branch not found"**

Here is the settings.yml we are using:
```yaml
repository:
  auto_init: true
  force_create: true
  private: true
  visibility: private
  has_issues: true
  has_projects: true
  has_wiki: true
  default_branch: main
  license_template: mit
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: false
  allow_update_branch: false
  archived: false
  security:
    enableVulnerabilityAlerts: true
    enableAutomatedSecurityFixes: true
    
branches:
  - name: default
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        require_last_push_approval: false
        bypass_pull_request_allowances: 
          apps: []
          users: []
          teams: []
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: false

      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: []

rulesets:
  - name: Template
    target: branch
    enforcement: active
    bypass_actors: []
   
    conditions:
      ref_name:
        include: ["~DEFAULT_BRANCH"]

    rules:
      - type: creation
      - type: update
        parameters:
          update_allows_fetch_and_merge: true
      - type: deletion
      - type: required_linear_history
      - type: required_signatures

      - type: pull_request
        parameters:
          dismiss_stale_reviews_on_push: false
          require_code_owner_review: false
          require_last_push_approval: false
          required_approving_review_count: 1
          required_review_thread_resolution: false
```
