### ISSUE TITLE
Setting teams in the global settings.yml wipes out all teams in all repos in the whole org

### ISSUE THREAD

**Issue by justinmchase** [github/safe-settings#432]
## Problem Description

I went to add a team to all repos, by setting one team in the settings.yml file into the teams section it wiped out all of the teams in all the repos in the whole org, except for those who also had suborgs and/or individual repo files.

### What is actually happening

It calculates changes for the settings.yml to affect all repos, for each repo it calculates it should have only that one team.

### What is the expected behavior

I would expect any repo affected by a change to the settings.yml file should have _additive_ changes only. If it also has a suborg and/or repo file then it could be definitive but with only the settings file being applied it should be additive.

Optionally, there needs to be a way to define the behavior for teams such as:

```yml
teams:
  add: 
    - name: global-security-team
      permission: read
```

### Error output, if available

```
N/A
```

### Are you using the hosted instance of probot/settings or running your own?

my own

### If running your own instance, are you using it with github.com or GitHub Enterprise?

enterprise

#### Version of probot/settings

`2.0.21-rc.8`

#### Version of GitHub Enterprise

not sure.

**Comment by svg153** [comment]
I think the main idea of this project is that the project acts as ["A single point of truth"](https://github.com/github/safe-settings/issues/350#issuecomment-1403951756) in everything it can manage. Except for labels, because many apps create their own and it would be more difficult to manage.

It is true, that because of this, the migration is more "complex". If the tool provided a way to generate the configuration files taking what is configured in GitHub, it would be much simpler. As this is not the case, you can always make a quick script.

But, it would be nice if there was something in the README.md [advising how it works](https://github.com/github/safe-settings/issues/339#issuecomment-1330590800) and this possible problem.

PD: possible duplication with https://github.com/github/safe-settings/issues/350

**Comment by justinmchase** [comment]
I don't mind that it _can_ set the teams precisely, overriding what teams are set in each repo. If that's what I wanted to do, then it would be a huge life saver.

But it seems like in the settings.yml, more often then not its not really practical to set the teams for _all_ the repos to be just that one set. If they don't also have a matching suborg or repo specific file then its pretty aggressive. I can't have any shared teams in that file.

As you said  the labels have include/exclude logic because "many apps create their own", but similarly repos tend to create and assign their own teams. Managing that at the settings.yml file seems not totally practical; they'll all be the same.

**Comment by svg153** [comment]
I may have misunderstood you. But within each file associated with a repository, you can put the teams you want to have permissions to that particular repository. Example:

We have this config:

file and folder tree
```txt
# admin repo 
.github
├── repos
│   ├── api.yml
│   ├── devs-team.yml
│   ├── infra.yml
├── settings.yml
```

`settings.yml`:
```yaml
repository:
  auto_init: true
  private: true
  visibility: private
  ...
teams:
  - name: management
    permission: admin
...
```

`api.yml`:
```yaml
repository:
  name: api
teams:
  - name: infra
    permission: admin
  - name: devs
    permission: push
...
```

`devs-team.yml`:
```yaml
repository:
  name: devs-team
teams:
  - name: management
    permission: pull
  - name: devs
    permission: admin
...
```

`infra.yml`:
```yaml
repository:
  name: infra
teams:
  - name: infra
    permission: admin
  - name: devs
    permission: push
...
```

And this would look like this:

- NOTE: `management` has admin permissions on all repositories.
- The `api` repository:
  - `management` has admin permissions (inherited)
  - `infra` has admin permissions
  - `devs` has push permissions
- The `devs-team` repository:
  - `management` has pull permissions (downgraded).
  - `devs` has admin permissions
- The `infra` repository:
  - `management` has administrator permissions (inherited)
  - `infra` has admin permissions
  - `devs` has push permissions
---

What you cannot do as far as I know is to configure the members of a team, nor directly configure which repositories the team has access to.
