### ISSUE TITLE
suborgteams should allow specifying permissions on a repo(Ex: maintain)

### ISSUE THREAD

**Issue by L1ghtman2k** [github/safe-settings#494]
## New Feature

Please describe the desired new functionality:
 
When specifying suborgteams, I would like to be able to select repos that a team has Maintain permissions to(rather than Read/Write).

Perhaps something along the lines of:
```
suborgteams:
  "XYZ-team":
    permissions: ["Maintain", "Admin"]
    exclude_list: ["exception_repo*"] # Optional, just thought this might fit this structure, in case this needs to be supported in the future
```
