### ISSUE TITLE
Turn off `required_pull_request_reviews` fails with `TypeError`

### ISSUE THREAD

**Issue by paddyroddy** [github/safe-settings#541]
## Problem Description
Setting `required_pull_request_reviews` to `null` fails.

### What is actually happening
In the dry run on pull request I get a `TypeError` with the following settings
```yaml
branches:
  # `default` creates a branch protection rule to against the repo's base branch
  - name: default
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - linting
      enforce_admins: true
      restrictions: null
```

### What is the expected behavior
That this setting should be disabled, I was following the instructions here https://github.com/github/safe-settings/blob/4cca3b0a6b362e7f874ecc3571ff8e1d7ab4671e/README.md?plain=1#L449-L450

### Error output, if available

```
Breakdown of errors

admin: TypeError: Cannot read properties of null (reading 'required_approving_review_count')
```
https://github.com/paddyroddy/admin/pull/1/checks

### Are you using the hosted instance of probot/settings or running your own?
Hosted instance https://github.com/apps/safe-settings-app

**Comment by decyjphr** [comment]
Sorry, the documentation is incorrectly worded (by null it should be empty) So, you can just set it empty as follows:
```
branches:   
  - name: default 
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
```


I ran this on the latest version and the PR check is shown below:


![Image](https://github.com/github/safe-settings/assets/57544838/e3f722e5-b925-4930-9e93-cd772d99e028)
