### ISSUE TITLE
Help with Setup with docker and Other bugs 

### ISSUE THREAD

**Issue by bheemvennapureddy** [github/safe-settings#545]
Few Questions : 

1. if we are using Github Enterprise Cloud or is this only Self hosted github ?
2. From Setup point of view if we run the app ( say on a Ec2 ) we don't run or setup the the docker version of the app if i am correct.
3. Is there a easier way to test this ?

**Comment by bheemvennapureddy** [comment]
Seeing discrepancies with docker run not sure what i am missing - the app couldn't listen to the events from localhost where npm run dev works as usual here is the docker compose 

<img width="765" alt="Screenshot 2023-10-30 at 11 29 50 PM" src="https://github.com/github/safe-settings/assets/144472943/d01e6823-6afd-4335-bd4f-45ae416e4a7a">

logs 

<img width="766" alt="Screenshot 2023-10-30 at 11 29 26 PM" src="https://github.com/github/safe-settings/assets/144472943/2396b6f2-271d-47de-a181-9a060d791791">

npm run dev fails here and there but atleast runs 

<img width="755" alt="Screenshot 2023-10-30 at 10 19 17 PM" src="https://github.com/github/safe-settings/assets/144472943/0a913141-dc31-4617-9cfe-bae1929b9684">

**Comment by bheemvennapureddy** [comment]
What am i missing here if the probot app fails to post somethin check-run doesn't fail keeps running for ever 

<img width="1452" alt="Screenshot 2023-10-30 at 10 46 41 PM" src="https://github.com/github/safe-settings/assets/144472943/ad754214-5f71-4de5-a7d4-414156ba52e1">

Failure from probot 

<img width="755" alt="Screenshot 2023-10-30 at 10 19 17 PM" src="https://github.com/github/safe-settings/assets/144472943/ae4d3091-8986-4bda-8d13-49387670652a">

**Comment by bheemvennapureddy** [comment]
Few more logs 
<img width="746" alt="Screenshot 2023-10-31 at 12 01 06 AM" src="https://github.com/github/safe-settings/assets/144472943/b5ca1bf5-e531-4026-8e94-ddd1630a98ee">

**Comment by bheemvennapureddy** [comment]
@decyjphr  can you give me some insights on this any help on this will be really appreciated. Thanks in advance

**Comment by decyjphr** [comment]
@bheemvennapureddy I'll get a patch release which should address your issue. I'll update this issue in a few hours when that is available.

**Comment by decyjphr** [comment]
@bheemvennapureddy can you try your testing with `2.1.1-rc.1` image and let me know?

**Comment by bheemvennapureddy** [comment]
@decyjphr will test in couple hours

**Comment by bheemvennapureddy** [comment]
@decyjphr which issues does this fix ?

**Comment by bheemvennapureddy** [comment]
@decyjphr never ending check is gone now but seeing a diff error on applying branch protection rules 

```
"text": "Run on: `2023-11-02T06:26:52.683Z`\n\n#### Breakdown of Errors\n| Owner| Repo | Plugin | Error \n| --- | --- | --- | --- \nCuroFinTechCorp | safe-test | Branches | Error applying branch protection {&quot;name&quot;:&quot;HttpError&quot;,&quot;status&quot;:422,&quot;response&quot;:{&quot;url&quot;:&quot;https://api.github.com/repos/CuroFinTechCorp/safe-test/branches/master/protection&quot;,&quot;status&quot;:422,&quot;headers&quot;:{&quot;access-control-allow-origin&quot;:&quot;*&quot;,&quot;access-control-expose-headers&quot;:&quot;ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset&quot;,&quot;connection&quot;:&quot;close&quot;,&quot;content-length&quot;:&quot;299&quot;,&quot;content-security-policy&quot;:&quot;default-src &#39;none&#39;&quot;,&quot;content-type&quot;:&quot;application/json; charset=utf-8&quot;,&quot;date&quot;:&quot;Thu, 02 Nov 2023 06:26:52 GMT&quot;,&quot;referrer-policy&quot;:&quot;origin-when-cross-origin, strict-origin-when-cross-origin&quot;,&quot;server&quot;:&quot;GitHub.com&quot;,&quot;strict-transport-security&quot;:&quot;max-age=31536000; includeSubdomains; preload&quot;,&quot;vary&quot;:&quot;Accept-Encoding, Accept, X-Requested-With&quot;,&quot;x-accepted-github-permissions&quot;:&quot;administration=write&quot;,&quot;x-content-type-options&quot;:&quot;nosniff&quot;,&quot;x-frame-options&quot;:&quot;deny&quot;,&quot;x-github-api-version-selected&quot;:&quot;2022-11-28&quot;,&quot;x-github-media-type&quot;:&quot;github.v3; param=hellcat-preview.luke-cage-preview.zzzax-preview; format=json&quot;,&quot;x-github-request-id&quot;:&quot;5EAF:33C2:BED49A2:1879FB54:6543412C&quot;,&quot;x-ratelimit-limit&quot;:&quot;15000&quot;,&quot;x-ratelimit-remaining&quot;:&quot;14945&quot;,&quot;x-ratelimit-reset&quot;:&quot;1698909920&quot;,&quot;x-ratelimit-resource&quot;:&quot;core&quot;,&quot;x-ratelimit-used&quot;:&quot;55&quot;,&quot;x-xss-protection&quot;:&quot;0&quot;},&quot;data&quot;:{&quot;message&quot;:&quot;Invalid request.\\n\\nNo subschema in \\&quot;anyOf\\&quot; matched.\\nNo subschema in \\&quot;oneOf\\&quot; matched.\\nNot all subschemas of \\&quot;allOf\\&quot; matched.\\nFor &#39;anyOf/1&#39;, {\\&quot;contexts\\&quot;=&gt;[]} is not a null.&quot;,&quot;documentation_url&quot;:&quot;https://docs.github.com/rest/branches/branch-protection#update-branch-protection&quot;}},&quot;request&quot;:{&quot;method&quot;:&quot;PUT&quot;,&quot;url&quot;:&quot;https://api.github.com/repos/CuroFinTechCorp/safe-test/branches/master/protection&quot;,&quot;headers&quot;:{&quot;accept&quot;:&quot;application/vnd.github.hellcat-preview+json,application/vnd.github.luke-cage-preview+json,application/vnd.github.zzzax-preview+json&quot;,&quot;user-agent&quot;:&quot;probot/12.3.1 octokit-core.js/3.5.1 Node.js/21&quot;,&quot;authorization&quot;:&quot;token [REDACTED]&quot;,&quot;content-type&quot;:&quot;application/json; charset=utf-8&quot;},&quot;body&quot;:&quot;{\\&quot;required_pull_request_reviews\\&quot;:{\\&quot;required_approving_review_count\\&quot;:2,\\&quot;dismiss_stale_reviews\\&quot;:true,\\&quot;require_code_owner_reviews\\&quot;:false,\\&quot;require_last_push_approval\\&quot;:true,\\&quot;bypass_pull_request_allowances\\&quot;:{\\&quot;apps\\&quot;:[],\\&quot;users\\&quot;:[],\\&quot;teams\\&quot;:[]},\\&quot;dismissal_restrictions\\&quot;:{\\&quot;users\\&quot;:[],\\&quot;teams\\&quot;:[]}},\\&quot;required_status_checks\\&quot;:{\\&quot;contexts\\&quot;:[]},\\&quot;enforce_admins\\&quot;:true,\\&quot;restrictions\\&quot;:{\\&quot;apps\\&quot;:[],\\&quot;users\\&quot;:[],\\&quot;teams\\&quot;:[]}}&quot;,&quot;request&quot;:{&quot;retryCount&quot;:1}}}\n\n\n"
```

Settings.yml below 

```
# These settings are synced to GitHub by https://github.com/github/safe-settings

repository:
  # Settings for Code security and analysis
  # Dependabot Alerts
  security:
    enableVulnerabilityAlerts: true
    enableAutomatedSecurityFixes: true
  
  # Either `true` to make the repository private, or `false` to make it public. 
  # If this value is changed and if Org members cannot change the visibility of repos
  # it would result in an error when updating a repo
  private: true
  
  # Can be public or private. If your organization is associated with an enterprise account using 
  # GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+, visibility can also be internal. 
  visibility: private
  
  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true
  
  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: true
  
  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true
  
  # The default branch for this repository.
  default_branch: master
  
  # Desired language or platform [.gitignore template](https://github.com/github/gitignore) 
  # to apply. Use the name of the template without the extension. 
  # For example, "Haskell".
  gitignore_template: node
  
  # Choose an [open source license template](https://choosealicense.com/) 
  # that best suits your needs, and then use the 
  # [license keyword](https://help.github.com/articles/licensing-a-repository/#searching-github-by-license-type) 
  # as the `license_template` string. For example, "mit" or "mpl-2.0".
  license_template: mit
  
  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true
  
  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true
  
  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true
  
  # Either `true` to allow auto-merge on pull requests, 
  # or `false` to disallow auto-merge.
  # Default: `false`
  allow_auto_merge: true
  
  # Either `true` to allow automatically deleting head branches 
  # when pull requests are merged, or `false` to prevent automatic deletion.
  # Default: `false`
  delete_branch_on_merge: true  
      
  # Whether to archive this repository. false will unarchive a previously archived repository.
  archived: false

# The following attributes are applied to any repo within the org
# So if a repo is not listed above is created or edited
# The app will apply the following settings to it
labels:
  # Labels: define labels for Issues and Pull Requests
  include:
    - name: bug
      color: CC0000
      description: An issue with the system

    - name: feature
      # If including a `#`, make sure to wrap it with quotes!
      color: '#336699'
      description: New functionality.

    - name: first-timers-only
      # include the old name to rename an existing label
      oldname: Help Wanted
      color: '#326699'

    - name: new-label
      # include the old name to rename an existing label
      oldname: Help Wanted
      color: '#326699'
  exclude:
    # don't delete any labels created on GitHub that starts with "release"
    - name: ^release
    
branches:
  # If the name of the branch value is specified as `default`, then the app will create a branch protection rule to apply against the default branch in the repo
  - name: default
    # https://docs.github.com/en/rest/reference/branches#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 2
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: false
        # Whether the most recent reviewable push must be approved by someone other than the person who pushed it.
        require_last_push_approval: true
        # Allow specific users, teams, or apps to bypass pull request requirements. Set to null to disable.
        bypass_pull_request_allowances:
          apps: []
          users: []
          teams: []
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: []
          teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. The list of status checks to require in order to merge into this branch
       contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []
```

**Comment by bheemvennapureddy** [comment]
@decyjphr  My context object was wrong i got that fixed , but ideally i should have got notified when i updated that to wrong on the pull request validator but which went fine.

Post update to context protection applied successfully but how can we skip `Require branches to be up to date before merging`

<img width="594" alt="Screenshot 2023-11-02 at 1 45 20 AM" src="https://github.com/github/safe-settings/assets/144472943/78b3caeb-6487-49d9-ad90-f3b4d0aaa887">

**Comment by decyjphr** [comment]
I believe you can set 
```yaml
required_status_checks:
  strict: false
  contexts:[]
```
to disable `require branches to be up to date before merging`
