### ISSUE TITLE
required_status_checks (contexts in settings.yml ) doesn't work with reusable workflows

### ISSUE THREAD

**Issue by bheemvennapureddy** [github/safe-settings#554]
required_status_checks doesn't work with reusable workflows, works if the same workflow is part of the repo not a resuable workflow

<img width="933" alt="Screenshot 2023-11-14 at 8 22 27 PM" src="https://github.com/github/safe-settings/assets/144472943/b80230eb-9f1d-4aed-bb9c-c68959e4c9d5">
<img width="926" alt="Screenshot 2023-11-14 at 8 23 27 PM" src="https://github.com/github/safe-settings/assets/144472943/b14f9bbc-60e9-4dec-a45c-266196df12e5">

**Comment by bheemvennapureddy** [comment]
@decyjphr  am i missing anything or should this be a github issue vs a safe settings issue ?

**Comment by bheemvennapureddy** [comment]
<img width="855" alt="Screenshot 2023-11-14 at 10 30 22 PM" src="https://github.com/github/safe-settings/assets/144472943/159c32c3-c2e8-467b-8980-db8d3189e443">

**Comment by adrianschmidt** [comment]
You need to include the `work_item_validation / ` part in the config. So I think the config should be changed like this:

```diff
-          - validate_work_item
+          - work_item_validation / validate_work_item
```

I'm not 100 % sure, because our configs use a slightly different syntax:

```yaml
branches:
  - name: default
    protection:
      required_status_checks:
        checks: [
          {
            "context": "work_item_validation / validate_work_item",
            "app_id": <integer here, I don't know if it's secret or not, so I redacted it to be on the safe side>
          }
        ]
```
