### ISSUE TITLE
Collaborators are not watched when empty

### ISSUE THREAD

**Issue by JakubBiel** [github/safe-settings#619]
## Problem Description
I appreciate this might be a limitation around GitHub API but when repository collaborators are empty, safe-settings won't modify the collaborators if an individual user has been added.
### What is actually happening
Example config for repository
```
collaborators: []

teams:
  - name: some-team
    permission: admin
  - name: some-other-team
    permission: push
```
With this config, if a single collaborator (not a team) is given access manually it will go undetected, i.e. safe-settings will not remove the rogue collaborator.
### What is the expected behavior
Manually added single collaborator is removed if not present in the settings.
### Error output, if available

```

```
