### ISSUE TITLE
Actions configuration in the repositories

### ISSUE THREAD

**Issue by jmencianaranjo-ionos** [github/safe-settings#656]
## Prerequisites:
[GitHub Actions Settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository)

#### Manage action permissions:
- [Get Permissions](https://docs.github.com/en/rest/actions/permissions?apiVersion=2022-11-28#get-github-actions-permissions-for-a-repository)
- [Set Permissions](https://docs.github.com/en/rest/actions/permissions?apiVersion=2022-11-28#set-github-actions-permissions-for-a-repository)
#### Manage actions access
- [Get Access](https://docs.github.com/en/rest/actions/permissions?apiVersion=2022-11-28#get-the-level-of-access-for-workflows-outside-of-the-repository)
- [Set Access](https://docs.github.com/en/rest/actions/permissions?apiVersion=2022-11-28#set-the-level-of-access-for-workflows-outside-of-the-repository)
### Manage Default Permissions
- [Get Default Permissions](https://docs.github.com/en/rest/actions/permissions?apiVersion=2022-11-28#get-default-workflow-permissions-for-a-repository)
- [Set Default Permissions](https://docs.github.com/en/rest/actions/permissions?apiVersion=2022-11-28#set-default-workflow-permissions-for-a-repository)

## New Feature
A section in the settings to enable or disable actions with a subroutine.
My usgerence for this would be:
- New plugin called Actions
- To set this up, it would look like this in a yml
```yaml
actions:
  permissions:
    enabled: true
    allowed_actions: all
    access:
        access_level: none
    workflow:
        default_workflow_permissions: read
        can_approve_pull_request_reviews: false
```
