### ISSUE TITLE
Label color parsing fails with scientific notation hex values

### ISSUE THREAD

**Issue by PendaGTP** [github/safe-settings#707]
## Problem Description

When label colors are specified without quotes in the YAML they could be interpreted as scientific notation (e.g. `5319e7`), they are incorrectly converted to decimal number

```yaml
labels:
  - name: "example"
    color: 5319e7  # 53190000000 instead of 5319e7
```

GitHub API return status code 422 since value is not a valid.

### What is actually happening

The label creation/update fails

### What is the expected behavior

Unquoted color values should be preserved as hex colors rather than being converted to decimal notation

### Error output, if available

```json
{
  "message": "Validation Failed",
  "errors": [{ "resource": "Label", "code": "invalid", "field": "color" }]
}
```
