### ISSUE TITLE
Config merge not working as expected for settings files

### ISSUE THREAD

**Issue by riprasad** [github/safe-settings#723]
## Problem Description

As stated in the README

> The precedence order for settings file is repository > suborg > org (.github/repos/.yml > .github/suborgs/.yml > .github/settings.yml)

This implies that if the same configuration(s) are defined at different levels, the settings defined at the repository level should take precedence. However, this is not happening as expected. I discovered that the issue stems from the way `safe-settings` creates the final merged config from the settings files. The merge process does a union of the suborg and repo level settings file, which brings back the deleted configs and also creates duplicate elements. There's also an edge case where the API call fails due to duplicate elements in the merged config.

### What is actually happening
I have configured a ruleset at the suborganization level that applies to multiple repositories and then modify the same ruleset for a particular repository in the repo level settings file.

**suborg/base-rulesets.yml**
```
suborgrepos:
  - '*'

rulesets:
  - name: Base Rulesets
    target: branch
    enforcement: active
    bypass_actors:
      - actor_id: 1
        actor_type: OrganizationAdmin
        bypass_mode: always

      - actor_id: 1097369
        actor_type: Integration
        bypass_mode: pull_request

      - actor_id: 11825178
        actor_type: Team
        bypass_mode: pull_request

    conditions:
      ref_name:
        include:
          - "refs/heads/rhoai-*"
        exclude: []

    rules:
      - type: deletion

      - type: non_fast_forward

      - type: pull_request
        parameters:
          required_approving_review_count: 0
          dismiss_stale_reviews_on_push: false
          require_code_owner_review: false
          require_last_push_approval: false
          required_review_thread_resolution: false
          allowed_merge_methods:
            - merge
            - squash
            - rebase
```

**repos/repo-name.yml**
```
rulesets:
  - name: Base Rulesets
    target: branch
    enforcement: active
    bypass_actors:
      - actor_id: 11825178
        actor_type: Team
        bypass_mode: pull_request

    conditions:
      ref_name:
        include:
          - "refs/heads/rhoai-*"
        exclude: []

    rules:
      - type: creation

      - type: non_fast_forward

      - type: pull_request
        parameters:
          required_approving_review_count: 1
          dismiss_stale_reviews_on_push: true
          require_code_owner_review: false
          require_last_push_approval: false
          required_review_thread_resolution: false
          allowed_merge_methods:
            - merge
            - squash
            - rebase
```

What's happening is that the configurations from the suborgs and repo level settings files are getting merged as shown below. The merge process does a union of the suborg and repo level settings file, which brings back the deleted configs and also creates duplicate elements(duplicate pull_request object, duplicate ref_name in conditions object).
```
target: "branch"
    enforcement: "active"
    bypass_actors: [
      {
        "actor_id": 1,
        "actor_type": "OrganizationAdmin",
        "bypass_mode": "always"
      },
      {
        "actor_id": 1097369,
        "actor_type": "Integration",
        "bypass_mode": "pull_request"
      },
      {
        "actor_id": 11825178,
        "actor_type": "Team",
        "bypass_mode": "pull_request"
      },
      {
        "actor_id": 11825178,
        "actor_type": "Team",
        "bypass_mode": "pull_request"
      }
    ]
    conditions: {
      "ref_name": {
        "include": [
          "refs/heads/rhoai-*",
          "refs/heads/rhoai-*"
        ],
        "exclude": []
      }
    }
    rules: [
      {
        "type": "deletion"
      },
      {
        "type": "non_fast_forward"
      },
      {
        "type": "pull_request",
        "parameters": {
          "required_approving_review_count": 0,
          "dismiss_stale_reviews_on_push": false,
          "require_code_owner_review": false,
          "require_last_push_approval": false,
          "required_review_thread_resolution": false,
          "allowed_merge_methods": [
            "merge",
            "squash",
            "rebase"
          ]
        }
      },
      {
        "type": "creation"
      },
      {
        "type": "non_fast_forward"
      },
      {
        "type": "pull_request",
        "parameters": {
          "required_approving_review_count": 1,
          "dismiss_stale_reviews_on_push": true,
          "require_code_owner_review": false,
          "require_last_push_approval": false,
          "required_review_thread_resolution": false,
          "allowed_merge_methods": [
            "merge",
            "squash",
            "rebase"
          ]
        }
      }
    ]
```

In the repository-level settings file, I made the below modifications to the rules, but few of them were not applied as expected:
- removed `deletion` rule - _**This rule was brought back due to the merge**_
- added `creation` rule _**Works as expected**_
- changed `required_approving_review_count` from _0_ to _1_ - _**Works as expected**_
- changed `dismiss_stale_reviews_on_push` from _false_ to _true_  - _**Works as expected**_
- removed `actor_id: 1` and `actor_id: 1097369` from _bypass_actors_ list - **_These actors were brought back due to merge_**. 

<br>
<br>

**Apart from this, the merge is also creating DUPLICATE PROPERTIES, which might be resulting in error** 
- If the ruleset exists, the app successfully sends a PUT request with the merged config as the request body([full logs](https://github.com/rhoai-rhtap/admin/actions/runs/12546266153/job/34981816239)). However, when the ruleset doesn't exist, the app makes a POST request with the same merged config, which leads to the below error([full logs](https://github.com/rhoai-rhtap/admin/actions/runs/12546352801/job/34982053584)).

> ERROR (HttpError): invalid json response body at https://api.github.com/repos/rhoai-rhtap/rhods-operator/rulesets reason: Unexpected end of JSON input
>     HttpError: invalid json response body at https://api.github.com/repos/rhoai-rhtap/rhods-operator/rulesets reason: Unexpected end of JSON input

<br>
- include": ["refs/heads/rhoai-*","refs/heads/rhoai-*"] is causing
<img width="787" alt="Screenshot 2024-12-30 at 4 26 21 PM" src="https://github.com/user-attachments/assets/d402951d-01d7-495d-8ef7-8ffb73f1b194" />. 

### What is the expected behavior

The Rulesets created for the repository should exactly match the configuration defined in the repository-level settings file.
- Rules removed from the repository-level settings file should not be included in the ruleset.
- Actor IDs removed from the repository-level settings file should not appear in the bypass actors.

In general - the merged config should not have duplicate elements and should not bring back deleted configurations in the repo level settings file. Safe-settings should consider the repository-level settings file as the source of truth and ensure that the precedence order is respected. Hopefully, it will also prevents API calls from failing due to duplicate elements in the request body.  

### Error output, if available
Full Logs - https://github.com/rhoai-rhtap/admin/actions/runs/12546352801/job/34982053584 
```
ERROR (HttpError): invalid json response body at https://api.github.com/repos/rhoai-rhtap/rhods-operator/rulesets reason: Unexpected end of JSON input
    HttpError: invalid json response body at https://api.github.com/repos/rhoai-rhtap/rhods-operator/rulesets reason: Unexpected end of JSON input
        at /home/runner/work/admin/admin/.safe-settings-code/node_modules/probot/node_modules/@octokit/request/dist-node/index.js:108:11
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async sendRequestWithRetries (/home/runner/work/admin/admin/.safe-settings-code/node_modules/octokit-auth-probot/node_modules/@octokit/auth-app/dist-node/index.js:398:12)
        at async Job.doExecute (/home/runner/work/admin/admin/.safe-settings-code/node_modules/bottleneck/light.js:405:18)
status: 500
request: {
    method: "POST"
    url: "https://api.github.com/repos/rhoai-rhtap/rhods-operator/rulesets"
    headers: {
      "accept": "application/vnd.github.v3+json",
      "user-agent": "probot/12.3.4 octokit-core.js/3.6.0 Node.js/20.18.1 (linux; x64)",
      "x-github-api-version": "2022-11-28",
      "authorization": "token [REDACTED]",
      "content-type": "application/json; charset=utf-8"
    }
    body: "{\"name\":\"Base Rulesets\",\"target\":\"branch\",\"enforcement\":\"active\",\"bypass_actors\":[{\"actor_id\":1,\"actor_type\":\"OrganizationAdmin\",\"bypass_mode\":\"always\"},{\"actor_id\":1097369,\"actor_type\":\"Integration\",\"bypass_mode\":\"pull_request\"},{\"actor_id\":11825178,\"actor_type\":\"Team\",\"bypass_mode\":\"pull_request\"},{\"actor_id\":11825178,\"actor_type\":\"Team\",\"bypass_mode\":\"pull_request\"}],\"conditions\":{\"ref_name\":{\"include\":[\"refs/heads/rhoai-*\",\"refs/heads/rhoai-*\"],\"exclude\":[]}},\"rules\":[{\"type\":\"deletion\"},{\"type\":\"non_fast_forward\"},{\"type\":\"pull_request\",\"parameters\":{\"required_approving_review_count\":0,\"dismiss_stale_reviews_on_push\":false,\"require_code_owner_review\":false,\"require_last_push_approval\":false,\"required_review_thread_resolution\":false,\"allowed_merge_methods\":[\"merge\",\"squash\",\"rebase\"]}},{\"type\":\"creation\"},{\"type\":\"non_fast_forward\"},{\"type\":\"pull_request\",\"parameters\":{\"required_approving_review_count\":1,\"dismiss_stale_reviews_on_push\":true,\"require_code_owner_review\":false,\"require_last_push_approval\":false,\"required_review_thread_resolution\":false,\"allowed_merge_methods\":[\"merge\",\"squash\",\"rebase\"]}}]}"
    request: {
      "retryCount": 3,
      "retries": 3,
      "retryAfter": 16
    }
}
```

### Are you using the hosted instance of probot/settings or running your own?
Running a full sync using Github Action

#### Version of probot/settings
2.1.14

**Comment by riprasad** [comment]
Tagging @decyjphr  to check if this is a known issue. I remember seeing a comment from you on an issue mentioning known problems with the merging logic, but I can’t seem to find the issue with that comment.

**Comment by PendaGTP** [comment]
Add ref to https://github.com/github/safe-settings/issues/655#issuecomment-2312189939 since this also seems related.

**Comment by decyjphr** [comment]
@riprasad seems like a bug is a valid one and the merging logic seems to be creating duplicates of bypass actors, rules, etc. will take a look at this.

**Comment by JTP3XP** [comment]
@decyjphr Do you know if this has been fixed? I'm using 2.1.14 to avoid the repo renaming issue in 2.1.16 but curious if there is already another version out there which fixes this, which I am also running into.

**Comment by cdav** [comment]
I am also running into this on 2.1.17

**Comment by decyjphr** [comment]
I'll look into this today.

**Comment by decyjphr** [comment]
I think we should not merge the suborg ruleset settings to the repo level ruleset settings, but create a new org level ruleset with the targeting based on the sub-org targeting. This will require some refactoring of the code. I can start looking into this.

**Comment by riprasad** [comment]
Hi @decyjphr, just circling back on this - it's been over 6 months since it was confirmed as a bug, and I was wondering if there’s been any progress or plans to address it. Totally understand things get busy, just wanted to bring it back on the radar :)

Thanks!

**Comment by jimisola** [comment]
Hit this on a 13-repo org and traced it to a specific line. Posting the root cause and a reproduction, since the thread describes the symptom well but I could not find the mechanism named anywhere in it. Also relevant to #722, which looks like the same defect.

## Root cause: `mergeBy` is called with one argument too few

`lib/mergeArrayBy.js:14` declares eight parameters:

```js
function mergeBy (key, configvalidator, overridevalidator, properties, target, source, options, githubContext) {
```

`lib/mergeDeep.js:333` calls it with **seven** arguments:

```js
const combined = mergeBy(key, this.configvalidators[key], this.overridevalidators[key], NAME_FIELDS, target[key], source[key], this.github)
```

So `this.github` binds to `options`, and `githubContext` is `undefined`.

`options` is passed straight into deepmerge at `lib/mergeArrayBy.js:24`:

```js
destination[matchingIndex] = merge(target[matchingIndex], sourceItem, options)
```

An Octokit client has no `arrayMerge`, so deepmerge silently falls back to its default — **concatenate**.

That is exactly the "union instead of precedence" this issue describes, and it explains why the behaviour is inconsistent by depth. The **top-level** array does merge by `NAME_FIELDS`, because `mergeBy` applies `findMatchingIndex` itself. Any array **nested inside a matched element** concatenates, because that path goes through plain deepmerge with a broken options object. So `rulesets` merge by `name` as intended, while the `rules` inside them do not merge by `type` — even though `type` is in `NAME_FIELDS` precisely so that they would.

## Reproduction

Org config, `required_status_checks` declared at both levels — the natural way to share org-wide contexts and add per-repo ones:

`suborgs/all.yml` (applies to all repos, `suborgrepos: ["*"]`):

```yaml
rulesets:
  - name: protect-main
    rules:
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: false
          required_status_checks:
            - context: "Analyze (actions)"
            - context: "CodeQL"
            - context: "DCO"
```

`repos/<repo>.yml`:

```yaml
rulesets:
  - name: protect-main
    rules:
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: false
          required_status_checks:
            - context: "build"
            - context: "lint / lint"
```

Expected: one rule, five contexts. Actual: the emitted payload contains **two** `required_status_checks` rules. I confirmed this by parsing all 13 `Updating Ruleset with the following values` payloads out of a debug-level run — every one had two.

## What GitHub then does, which is the part worth attention

The outcome is **not consistent**, and only one half is loud:

| repo already had a `required_status_checks` rule | PUT | result |
|---|---|---|
| no  (6 repos) | **422** `Invalid rule 'required_status_checks': ` | rules never applied |
| yes (7 repos) | **200** | second rule wins, first is **silently discarded** |

Identical config shape, identical two-rule payload, opposite outcomes — split entirely by prior state.

The `422` is the edge case this issue already mentions. The `200` is the one I would flag: on those seven repos the org-wide contexts were dropped without any error. One repo went from 8 required contexts to 5. Nothing in the log, nothing in the run status, nothing in the ruleset UI to indicate protection had been reduced — the sync reported success. A `422` is recoverable because you know. This is not.

Worth noting the error string itself is empty after the colon (`Invalid rule 'required_status_checks': `), which is likely what #1003 is about.

## Note for anyone verifying this

I first "verified" the config as safe with a harness that called `mergeBy` with its own `arrayMerge` in the `options` slot. It reported one correctly-merged rule and I shipped on that. Supplying valid options is what the calling code fails to do, so the harness was more capable than the code it stood in for and manufactured confidence. Passing `{}` — reproducing the seven-argument call — reports two rules for the same input.

## On a fix

Passing a proper `options` object (or an explicit `undefined` placeholder plus a real deepmerge config carrying an `arrayMerge` that recurses through `mergeBy`) looks like the direction, so nested arrays merge by `NAME_FIELDS` the way the top level already does.

I have not tested a patch and am not claiming this one change is sufficient — `githubContext` is also silently `undefined` today, which affects `overridevalidator.canOverride(...)` at `lib/mergeArrayBy.js:20`, so there may be more than one consequence of the same arity mismatch. Reporting the cause and the evidence rather than proposing a patch I have not validated.

Observed on 2.1.18; the same call site and signature are unchanged on `main-enterprise` as of today.
