### ISSUE TITLE
Full sync failures with >1 Environment variable

### ISSUE THREAD

**Issue by cdav** [github/safe-settings#805]
## Problem Description

Full sync failures issues when more than one repository variable is defined. 

### What is actually happening

I have a repository defined with two environment variables and a sub-org with one env var. The initial full sync for this repository successfully adds the environment variables. Subsequent full sync runs fail with `Error HttpError: Already exists - Variable already exists in Environments for repo: `

```
repository:
  name: safe-settings-test
  description: Testing safe-settigns

environments:
  - name: testenv
    variables:
      - name: REPO_VAR
        value: repo_value
      - name: REPO_VAR2
        value: repo_value2
```
```
suborgrepos:
  - safe-settings-test

environments:
  - name: testenv
    variables:
      - name: SUBORG_VAR
        value: suborg_value
```

If I remove the sub-org config and have two environment vars defined in the repo, each full sync swaps the vars on the repo. The current var is removed and replaced by the other defined.

### What is the expected behavior

Safe-setting successfully syncs.

### Error output, if available

```
Error HttpError: Already exists - Variable already exists in Environments for repo: {"owner":"<removed-for-issue-creation>","repo":"safe-settings-test"} entries [{"name":"testenv","variables":[{"name":"suborg_var","value":"suborg_value"},{"name":"repo_var","value":"repo_value"},{"name":"repo_var2","value":"repo_value2"}]}]
```

### Are you using the hosted instance of probot/settings or running your own?

Our own, using the helm chart.

### If running your own instance, are you using it with github.com or GitHub Enterprise?

github.com

#### Version of probot/settings

2.1.16

#### Version of GitHub Enterprise

n/a
