### ISSUE TITLE
Safe-settings doesn't create branch protection and org rulesets

### ISSUE THREAD

**Issue by Ali-Dalal** [github/safe-settings#842]
## Problem Description
I am trying to create branch protection via repo.yml as follow:
```yaml
repository:
  description: updated description from safe-settings
  branches:
  # If the name of the branch value is specified as `default`, then the app will create a branch protection rule to apply against the default branch in the repo
  - name: main # default doesn't work as well
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 3
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        bypass_pull_request_allowances:
          apps: []
          users: []
          teams: []
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: []
```

### What is actually happening
only description is being updated. in safe-settings pull request dry-run, I see that there are changes to be applied related to branch protection but after merging the pull-request, only description is being changed.

### What is the expected behavior
branch protection rule should be created

### Error output, if available
There are no errors. I can only see webhook successfully applied.
```

```

## Context
Also I tried to create org rulesets by adding a sample to `settings.yml` but also it is not creating but other settings like `topics` is creating. 
I tried to call GitHub api with same branch-protection-rule body and using same credentials (github-app) and the rule is created.

### Are you using the hosted instance of probot/settings or running your own?
own using docker image `ghcr.io/github/safe-settings:2.1.17`

### If running your own instance, are you using it with github.com or GitHub Enterprise?
GitHub Enterprise

#### Version of probot/settings
2.1.17

**Comment by rell-fastly** [comment]
We see the same behavior -- anything related to branch protection is not updated on a full sync or enforced via the webhook interceptions.

**Comment by mchittineni** [comment]
I’d really appreciate it if there’s a fix for this—I’ve been patiently testing various configurations to get the branch protection rules to work.

**Comment by Ali-Dalal** [comment]
Branch protection still doesn't work in any case. 

what worked for us so far is to use Ruleset.

**Comment by aakash-pinc** [comment]
Repo level ruleset is working, but org level ruleset is not working for me. 

@Ali-Dalal , is org level ruleset working for you?  We have the below content in `.github/settings.yml` file but not working. 

```yaml
# Rulesets
# Ref: https://docs.github.com/en/rest/orgs/rules?apiVersion=2022-11-28#create-an-organization-repository-ruleset
rulesets:
# Branch protection for all the sara-*
- name: sara-branch-protection
  target: branch
  enforcement: active
  conditions:
    ref_name:
      include: ["~DEFAULT_BRANCH","refs/heads/develop"]
      exclude: []
    repository_name:
      include: ["sara-*"]
      exclude: []
      protected: false

  rules:
    - type: deletion
    - type: non_fast_forward
    - type: pull_request
      parameters:
        dismiss_stale_reviews_on_push: true
        require_code_owner_review: true
        require_last_push_approval: true
        required_approving_review_count: 1
        required_review_thread_resolution: true
        automatic_copilot_code_review_enabled: true
        allowed_merge_methods: ["merge","squash"]
```
