### ISSUE TITLE
Can I create environment and environment variables under this in a repo using github safe-settings admin repo ?

### ISSUE THREAD

**Issue by sowmiya99** [github/safe-settings#850]
## Prerequisites:

Can I create environment and environment variables under this in a repo using github safe-settings admin repo ?

I have 70+ repositories , which needs the same environment and same set of variables.
I'm trying to create an environment and variables under it for repository like sr-*

Does safe setting support this ?

This is the yaml file I placed under suborgs/sr.yml

```
# Microservice repo environmental variables settings
suborgrepos:
  - sr-*

repository:
  environments:
    deployment:
      environment_variables:
        tag: "test"
        service_account_name: "ss-fab"
```

**Comment by MathConstant** [comment]
yes you can
i have applied this one
```
suborgproperties:
  - repository_type: cloud

repository:

environments:
  - name: prod
    wait_timer: 0
    deployment_branch_policy:
      protected_branches: false
      custom_branch_policies:
        - names: ["main"]
          type: branch
    variables:
      - name: TEST_VAR_ENV
        value: "test"
```

a note though is that it looks like the validator doesn't support environments atm so you don't get any info from the dry run
